export default {
  homeIcon: require('../assets/Images/home.png'),
  voiceIcon: require('../assets/Images/voice.png'),
  whitecartIcon: require('../assets/Images/whitecart.png'),
  searchIcon: require('../assets/Images/search.png'),
  bellIcon: require('../assets/Images/bell.png'),
  bagIcon: require('../assets/Images/bag.png'),
  brandIcon: require('../assets/Images/brand.png'),
  starIcon: require('../assets/Images/star.png'),
  accountIcon: require('../assets/Images/account.png'),
  headerLogo: require('../assets/Images/headerLogo.png'),
  wishListIcon: require('../assets/Images/wishlist.png'),
  profileIcon: require('../assets/Images/account.png'),
  profileActiveIcon: require('../assets/Images/account-active.png'),
  starActiveIcon: require('../assets/Images/starActive.png'),
  categoriesIcon: require('../assets/Images/categories.png'),
  homeActiveIcon: require('../assets/Images/home-active.png'),
  wishListActiveIcon: require('../assets/Images/wishlist-active.png'),
  categoriesActiveIcon: require('../assets/Images/categories-active.png'),
};
